[project]
name = "hackathon-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elevenlabs>=2.16.0",
    "openai-agents>=0.3.3",
    "sounddevice>=0.5.2",
    "vosk>=0.3.45",
]
